### PR TITLE
fix "(node) Buffer.set is deprecated. Use array indexes instead."

### PR DESCRIPTION
**Pull request by cloudop**
It will cause buffer bytes been 0 from index 1.Like below.
<Buffer 1c 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>

### CODE REVIEW

**Comment by ealmansi** [comment]
@cloudop Thanks for your contribution.

The deprecated set and get methods have been removed from Buffer [1], and the set method being used here is actually Uint8Array.prototype.set, which is still very much in use. Buffer instances are also Uint8Array instances [2].

[1] https://github.com/nodejs/node/commit/101bca988cebce584d5b6098c316a6e7bf89b69d
[2] https://nodejs.org/api/buffer.html#buffer_buffers_and_typedarray

**Comment by cloudop** [comment]
Thanks for your answer. I know what you mean. 
`toBitpayAddress('17Wk4GPKw9nZ9PbspzaxN3fv1L2m9NA9dg')`
It will always return QLbz7JHiBTspS962RLKV8GndWFwjA5K66,but the correct address is CNyddJjPpCm63XWJWjuswZHwdTFB5Cvqbq
I only modify the encodeAsBitpay and encodeAsLegacy

**Comment by ealmansi** [comment]
If you try this address you mention on the online demo, you get the correct result:

https://bitcoincashjs.github.io/address/

I believe you're running an old version of node, previous to v6 where Buffer.set was removed.

**Comment by cloudop** [comment]
Oh，I see. My node version is v4.7.2.

**Comment by ealmansi** [comment]
Thanks for opening this. Using an old version of node should either work or fail gracefully, but it should definitely not return an invalid address.

**Pull request closed without merging**
